"use client"

import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Progress } from "@/components/ui/progress"
import { Button } from "@/components/ui/button"
import { Target, CheckCircle2, TrendingUp, Plus } from "lucide-react"
import { motion } from "framer-motion"

interface WeeklyGoal {
  id: string
  title: string
  current: number
  target: number
  unit: string
  priority: "high" | "medium" | "low"
  autoGenerated: boolean
}

const weeklyGoals: WeeklyGoal[] = [
  {
    id: "1",
    title: "Post 2 updates",
    current: 1,
    target: 2,
    unit: "posts",
    priority: "high",
    autoGenerated: true,
  },
  {
    id: "2",
    title: "Finish course X",
    current: 85,
    target: 100,
    unit: "%",
    priority: "high",
    autoGenerated: true,
  },
  {
    id: "3",
    title: "Update portfolio",
    current: 0,
    target: 1,
    unit: "update",
    priority: "medium",
    autoGenerated: true,
  },
  {
    id: "4",
    title: "Engage with 5 posts",
    current: 3,
    target: 5,
    unit: "engagements",
    priority: "medium",
    autoGenerated: false,
  },
]

export function GoalsForWeek() {
  const completedGoals = weeklyGoals.filter(
    (goal) => goal.current >= goal.target
  ).length

  return (
    <Card className="border-border shadow-sm">
      <CardHeader className="pb-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-lg bg-blue-500/10 flex items-center justify-center">
              <Target className="h-5 w-5 text-blue-600" />
            </div>
            <div>
              <CardTitle className="text-lg font-bold">Goals for This Week</CardTitle>
              <CardDescription className="text-xs">
                Auto-generated goal cards
              </CardDescription>
            </div>
          </div>
          <Badge variant="outline" className="text-xs">
            {completedGoals} / {weeklyGoals.length} Complete
          </Badge>
        </div>
      </CardHeader>

      <CardContent className="space-y-4">
        {weeklyGoals.map((goal, index) => {
          const percentage = (goal.current / goal.target) * 100
          const isComplete = goal.current >= goal.target

          return (
            <motion.div
              key={goal.id}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: index * 0.1 }}
              className={`p-3 rounded-lg border transition-all ${
                isComplete
                  ? "bg-green-500/10 border-green-500/20"
                  : "bg-background border-border hover:border-primary/50"
              }`}
            >
              <div className="flex items-start justify-between gap-2 mb-2">
                <div className="flex items-center gap-2 flex-1">
                  {isComplete ? (
                    <CheckCircle2 className="h-4 w-4 text-green-600 shrink-0" />
                  ) : (
                    <Target className="h-4 w-4 text-blue-600 shrink-0" />
                  )}
                  <div className="flex-1 min-w-0">
                    <div className="font-semibold text-sm">{goal.title}</div>
                    {goal.autoGenerated && (
                      <Badge variant="outline" className="text-xs mt-1">
                        AI Generated
                      </Badge>
                    )}
                  </div>
                </div>
                <Badge
                  variant={
                    goal.priority === "high"
                      ? "destructive"
                      : goal.priority === "medium"
                      ? "default"
                      : "outline"
                  }
                  className="text-xs shrink-0"
                >
                  {goal.priority}
                </Badge>
              </div>
              <div className="flex items-center justify-between text-xs text-muted-foreground mb-2">
                <span>
                  {goal.current} / {goal.target} {goal.unit}
                </span>
                <span>{Math.round(percentage)}%</span>
              </div>
              <Progress value={percentage} className="h-2" />
              {isComplete && (
                <motion.div
                  initial={{ opacity: 0, scale: 0.9 }}
                  animate={{ opacity: 1, scale: 1 }}
                  className="text-xs text-green-600 font-medium mt-2"
                >
                  ✅ Goal achieved!
                </motion.div>
              )}
            </motion.div>
          )
        })}

        <Button variant="outline" className="w-full gap-2" size="sm">
          <Plus className="h-4 w-4" />
          Add Custom Goal
        </Button>
      </CardContent>
    </Card>
  )
}

